# Generated by Django 5.0 on 2023-12-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "rango",
                    models.CharField(
                        choices=[
                            ("R", "Recluta"),
                            ("S", "Soldado"),
                            ("C", "Cabo"),
                            ("Sgto", "Sargento"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_ingreso", models.DateField()),
                ("unidad", models.CharField(max_length=100)),
                ("especialidad", models.CharField(max_length=100)),
                ("grupo_sanguineo", models.CharField(max_length=5)),
                ("alergias", models.TextField(blank=True, null=True)),
                ("condiciones_medicas", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
